import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';
import cors from 'cors';
import dotenv from 'dotenv';
import { Resend } from 'resend';

// Load environment variables
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
const port = process.env.PORT || 3000;

const resend = new Resend(process.env.RESEND_API_KEY);

// Middleware
app.use(cors());
app.use(express.json());

// API Endpoint for Contact Form
app.post('/api/contact', async (req, res) => {
  try {
    const { firstName, lastName, phone, email, inquiryType, message } = req.body;

    const data = await resend.emails.send({
      from: 'onboarding@resend.dev', // Default testing address for Resend
      to: 'tadka.bombay@gmail.com',
      subject: `New Contact Form Submission: ${inquiryType}`,
      html: `
        <h2>New Contact Form Submission</h2>
        <p><strong>Name:</strong> ${firstName} ${lastName}</p>
        <p><strong>Phone:</strong> ${phone}</p>
        <p><strong>Email:</strong> ${email}</p>
        <p><strong>Inquiry Type:</strong> ${inquiryType}</p>
        <p><strong>Message:</strong></p>
        <p>${message}</p>
      `
    });

    res.status(200).json({ success: true, data });
  } catch (error) {
    console.error('Error sending email:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

// Path to the static files generated by Vite
const distPath = join(__dirname, 'dist');

// Check if dist exists, otherwise warn the user
if (!fs.existsSync(distPath)) {
  console.warn(`WARNING: The 'dist' directory does not exist at ${distPath}.`);
  console.warn(`Please run 'npm run build' before starting the server.`);
}

// Serve static files from the React app
app.use(express.static(distPath));

// The "catchall" handler: for any request that doesn't
// match one above, send back React's index.html file.
app.get('*', (req, res) => {
  res.sendFile(join(distPath, 'index.html'));
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
