import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
const port = process.env.PORT || 3000;

// Path to the static files generated by Vite
const distPath = join(__dirname, 'dist');

// Check if dist exists, otherwise warn the user
if (!fs.existsSync(distPath)) {
  console.warn(`WARNING: The 'dist' directory does not exist at ${distPath}.`);
  console.warn(`Please run 'npm run build' before starting the server.`);
}

// Serve static files from the React app
app.use(express.static(distPath));

// The "catchall" handler: for any request that doesn't
// match one above, send back React's index.html file.
app.get('*', (req, res) => {
  res.sendFile(join(distPath, 'index.html'));
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
